import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import SessionProvider from "@/components/SessionProvider";
import ToasterProvider from "@/providers/toast-provider";
import { cn } from "@/lib/utils";
import { AppContextProvider } from "@/providers/app-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" suppressHydrationWarning>
      <SessionProvider session={session}>
        <body className={cn("min-h-screen bg-[#f4f6f8]", inter.className)}>
          <AppContextProvider>{children}</AppContextProvider>
          <ToasterProvider></ToasterProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
